package lab_08_02;

import java.util.Arrays;
import java.util.List;

/**
 * Implement three different pricing models for an airline, and calculate the
 * revenue generated by each strategy (model) for computing the total revenue of
 * the airline's flights.
 *
 */
public class Client {

	public static void main(String[] args) {
		FlightRevenueCalculator calculator = new FlightRevenueCalculator();
		PriceModel singlePriceModel = new SinglePriceModel();
		PriceModel twoClassesModel = new TwoClassesModel();
		PriceModel multiClassModel = new MultiClassModel();

		List<Flight> flights = Arrays.asList(
				new Flight[] { new Flight(320), new Flight(200), new Flight(170), new Flight(150), new Flight(200) });

		calculator.setPriceModel(singlePriceModel);
		System.out.println(String.format("%-25s: $%,.2f", "Single price model", calculator.getRevenue(flights)));

		calculator.setPriceModel(twoClassesModel);
		System.out.println(String.format("%-25s: $%,.2f", "Two classes price model", calculator.getRevenue(flights)));

		calculator.setPriceModel(multiClassModel);
		System.out.println(String.format("%-25s: $%,.2f", "Multi class price model", calculator.getRevenue(flights)));
	}

}
